# Generated by Django 4.2.28 on 2026-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_secret', models.TextField(help_text='Encrypted or encoded shared secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session key was created')),
            ],
            options={
                'verbose_name': 'Session Key',
                'verbose_name_plural': 'Session Keys',
                'db_table': 'session_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
