# Generated by Django 4.2.28 on 2026-02-20 08:15

import crypto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionkey',
            name='expires_at',
            field=models.DateTimeField(default=crypto.models.default_expiry, help_text='When this session expires'),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this session is active (can be revoked)'),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the session was last modified'),
        ),
        migrations.AlterField(
            model_name='sessionkey',
            name='shared_secret',
            field=models.TextField(help_text='Hex-encoded shared secret (NEVER expose in API/admin)'),
        ),
        migrations.AddIndex(
            model_name='sessionkey',
            index=models.Index(fields=['is_active'], name='session_key_is_acti_548f85_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionkey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sender', 'receiver'), name='unique_active_session_per_pair'),
        ),
    ]
