# Generated by Django 4.2.28 on 2026-02-06 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transfer identifier', unique=True)),
                ('file_name', models.CharField(blank=True, help_text='Original file name at time of transfer', max_length=255)),
                ('encrypted_file_path', models.TextField(blank=True, help_text='Path to the encrypted file', null=True)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', help_text='Encryption algorithm used for this transfer', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connecting', 'Connecting'), ('key_exchange', 'Key Exchange'), ('transferring', 'Transferring'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current transfer status', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Transfer progress percentage (0-100)')),
                ('bytes_transferred', models.BigIntegerField(default=0, help_text='Bytes transferred so far')),
                ('transfer_speed', models.FloatField(default=0, help_text='Current transfer speed in bytes/second')),
                ('error_message', models.TextField(blank=True, help_text='Error message if transfer failed', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of retry attempts')),
                ('connection_id', models.CharField(blank=True, help_text='WebRTC connection identifier', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When transfer was initiated')),
                ('started_at', models.DateTimeField(blank=True, help_text='When actual transfer started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transfer completed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('file', models.ForeignKey(help_text='File being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='files.file')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('created', 'Transfer Created'), ('status_changed', 'Status Changed'), ('progress_update', 'Progress Updated'), ('connection_established', 'Connection Established'), ('key_exchanged', 'Keys Exchanged'), ('chunk_completed', 'Chunk Completed'), ('error', 'Error Occurred'), ('retry', 'Retry Attempted')], help_text='Type of event', max_length=30)),
                ('old_status', models.CharField(blank=True, help_text='Previous status (for status changes)', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, help_text='New status (for status changes)', max_length=20, null=True)),
                ('message', models.TextField(blank=True, help_text='Log message details', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event data', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When event occurred')),
                ('transfer', models.ForeignKey(help_text='Associated transfer', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transfers.transfer')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'verbose_name_plural': 'Transfer Logs',
                'db_table': 'transfer_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
