# Generated by Django 4.2.28 on 2026-02-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionkey',
            name='receiver',
            field=models.ForeignKey(help_text='User who receives the session', on_delete=django.db.models.deletion.CASCADE, related_name='session_keys_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionkey',
            name='sender',
            field=models.ForeignKey(help_text='User who initiated the session', on_delete=django.db.models.deletion.CASCADE, related_name='session_keys_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sessionkey',
            index=models.Index(fields=['sender', 'receiver'], name='session_key_sender__88b5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionkey',
            index=models.Index(fields=['-created_at'], name='session_key_created_b21ce1_idx'),
        ),
    ]
