# Generated by Django 4.2.28 on 2026-02-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='receiver',
            field=models.ForeignKey(help_text='User receiving the file', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(help_text='User sending the file', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender', 'status'], name='transfers_sender__da98ff_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['receiver', 'status'], name='transfers_receive_4b9824_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', '-created_at'], name='transfers_status_593d59_idx'),
        ),
    ]
