# Generated by Django 4.2.28 on 2026-03-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_sessionkey_expires_at_sessionkey_is_active_and_more'),
        ('transfers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='encrypted_aes_key',
            field=models.TextField(blank=True, help_text='Base64-encoded AES key encrypted with ECDH shared secret', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='key_iv',
            field=models.CharField(blank=True, help_text='Hex-encoded IV used to encrypt the AES key', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='key_tag',
            field=models.CharField(blank=True, help_text='Hex-encoded authentication tag for encrypted AES key', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session key used for ECDH key exchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='crypto.sessionkey'),
        ),
    ]
