# Generated by Django 4.2.28 on 2026-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_add_encrypted_aes_key_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connecting', 'Connecting'), ('key_exchange', 'Key Exchange'), ('transferring', 'Transferring'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current transfer status', max_length=20),
        ),
    ]
