# Generated by Django 4.2.28 on 2026-02-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_private_key', models.TextField(help_text='Fernet-encrypted ECDH private key (PEM format)')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for key rotation tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the private key was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the private key was last updated')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='private_key_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Private Key',
                'verbose_name_plural': 'User Private Keys',
                'db_table': 'user_private_keys',
            },
        ),
    ]
