# Generated by Django 4.2.28 on 2026-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat timestamp — used to compute real-time online status', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether user is currently online (legacy flag — use last_seen for accuracy)'),
        ),
    ]
