# Generated by Django 4.2.28 on 2026-02-06 08:30

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the file', unique=True)),
                ('name', models.CharField(help_text='Stored filename (may be sanitized)', max_length=255)),
                ('original_name', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='application/octet-stream', help_text='MIME type of the file', max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum for integrity verification', max_length=64, null=True)),
                ('is_encrypted', models.BooleanField(default=True, help_text='Whether file is encrypted for transfer')),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', help_text='Encryption algorithm used', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When file metadata was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('file_path', models.FileField(blank=True, help_text='Optional local storage path', null=True, upload_to=files.models.get_file_upload_path)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_number', models.PositiveIntegerField(help_text='Chunk sequence number (1-indexed)')),
                ('total_chunks', models.PositiveIntegerField(help_text='Total number of chunks')),
                ('size', models.PositiveIntegerField(help_text='Chunk size in bytes')),
                ('offset', models.BigIntegerField(default=0, help_text='Byte offset in original file')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum for chunk', max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Chunk transfer status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(help_text='Parent file', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.file')),
            ],
            options={
                'verbose_name': 'File Chunk',
                'verbose_name_plural': 'File Chunks',
                'db_table': 'file_chunks',
                'ordering': ['file', 'chunk_number'],
            },
        ),
    ]
