# Generated by Django 4.2.28 on 2026-02-20 09:02

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_sessionkey_expires_at_sessionkey_is_active_and_more'),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypted_file',
            field=models.FileField(blank=True, help_text='Encrypted file content (AES-256-GCM ciphertext)', null=True, upload_to=files.models.get_encrypted_file_path),
        ),
        migrations.AddField(
            model_name='file',
            name='is_decrypted',
            field=models.BooleanField(default=False, help_text='Whether file has been decrypted by receiver'),
        ),
        migrations.AddField(
            model_name='file',
            name='iv',
            field=models.CharField(blank=True, help_text='Hex-encoded AES-GCM initialization vector (12 bytes)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session key used for encryption (for decryption lookup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_files', to='crypto.sessionkey'),
        ),
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.CharField(blank=True, help_text='Hex-encoded AES-GCM authentication tag (16 bytes)', max_length=48, null=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', '-uploaded_at'], name='files_owner_i_56c1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_encrypted'], name='files_is_encr_7bf23b_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['session'], name='files_session_e95f6a_idx'),
        ),
    ]
