# Generated by Django 4.2.28 on 2026-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_encrypted_file_file_is_decrypted_file_iv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times file has been downloaded'),
        ),
        migrations.AddField(
            model_name='file',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='When file was first successfully decrypted and downloaded', null=True),
        ),
    ]
