# Generated by Django 4.2.28 on 2026-03-12 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0004_alter_transfer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_file_download_count_file_downloaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the log entry', unique=True)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Changed'), ('registration', 'User Registration'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_delete', 'File Deleted'), ('file_view', 'File Viewed'), ('transfer_initiate', 'Transfer Initiated'), ('transfer_accept', 'Transfer Accepted'), ('transfer_reject', 'Transfer Rejected'), ('transfer_complete', 'Transfer Completed'), ('transfer_failed', 'Transfer Failed'), ('transfer_cancel', 'Transfer Cancelled'), ('key_exchange', 'Key Exchange'), ('key_generated', 'Keys Generated'), ('session_created', 'Session Created'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('invalid_token', 'Invalid Token'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('profile_update', 'Profile Updated'), ('user_online', 'User Online'), ('user_offline', 'User Offline')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='success', help_text='Outcome status of the action', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('related_file', models.ForeignKey(blank=True, help_text='Related file if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='files.file')),
                ('related_transfer', models.ForeignKey(blank=True, help_text='Related transfer if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='transfers.transfer')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='activity_lo_user_id_ce480c_idx'), models.Index(fields=['action', 'timestamp'], name='activity_lo_action_fe3d88_idx'), models.Index(fields=['status', 'timestamp'], name='activity_lo_status_e42a80_idx')],
            },
        ),
    ]
